services:
  postgres:
    image: postgres:15-alpine
    container_name: secure_storage_db
    environment:
      POSTGRES_DB: secure_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secure_storage_backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d secure_storage"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 